version: "3.7"
services:
  pixelpusher:
    container_name: pixelpusher
    image: pixelpusher:latest
    environment:
      - "DBDIR=/go/src/github.com/IoTPanic/pixelpusher/db/"
      - "MQTT=mqtt-broker:1883"
      - "MQTT-USERNAME="
      - "MQTT-PASSWORD="
      - "REDIS=redis:6379"
    ports:
      - "8080:8080"
    volumes:
      - "./db/:/go/src/github.com/IoTPanic/pixelpusher/db/"
    links:
      - "mqtt:broker"
  mqtt:
    container_name: mqtt-broker
    image: hivemq/hivemq4
    hostname: mqtt
    expose:
      - "9001"
      - "1883"
    ports:
      - "1883:1883"
      - "9001:9001"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always


# /mosquitto/config/mosquitto.conf