version: "3.7"
services:
  mongo:
    container_name: mongodb
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - db-data:/data/db
  pixelpusher:
    container_name: pixelpusher
    image: pixelpusher
    ports:
      - "8080:8080"
  mqtt:
    container_name: mqtt-broker
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    configs:
      - source: mqttconfig
        target: /path/to/container/config/to/overwrite/config.conf
networks:
  pixelnet:

volumes:
  db-data:

configs:
  mqttconfig:
    file: ./mosquitto.conf

# /mosquitto/config/mosquitto.conf