// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobufs/api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceState int32

const (
	DeviceState_OFFLINE           DeviceState = 0
	DeviceState_CONNECTING_AUTH   DeviceState = 1
	DeviceState_CONNECTING_HALTED DeviceState = 2
	DeviceState_CONNECTED_WAITING DeviceState = 3
	DeviceState_OPERATING         DeviceState = 4
	DeviceState_STANDBY           DeviceState = 5
)

var DeviceState_name = map[int32]string{
	0: "OFFLINE",
	1: "CONNECTING_AUTH",
	2: "CONNECTING_HALTED",
	3: "CONNECTED_WAITING",
	4: "OPERATING",
	5: "STANDBY",
}

var DeviceState_value = map[string]int32{
	"OFFLINE":           0,
	"CONNECTING_AUTH":   1,
	"CONNECTING_HALTED": 2,
	"CONNECTED_WAITING": 3,
	"OPERATING":         4,
	"STANDBY":           5,
}

func (x DeviceState) String() string {
	return proto.EnumName(DeviceState_name, int32(x))
}

func (DeviceState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d691f532c09db648, []int{0}
}

type MatrixType int32

const (
	MatrixType_SINGLEVALUE MatrixType = 0
	MatrixType_RGB         MatrixType = 1
	MatrixType_RGBW        MatrixType = 2
)

var MatrixType_name = map[int32]string{
	0: "SINGLEVALUE",
	1: "RGB",
	2: "RGBW",
}

var MatrixType_value = map[string]int32{
	"SINGLEVALUE": 0,
	"RGB":         1,
	"RGBW":        2,
}

func (x MatrixType) String() string {
	return proto.EnumName(MatrixType_name, int32(x))
}

func (MatrixType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d691f532c09db648, []int{1}
}

type Device struct {
	Id                   uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LongId               string      `protobuf:"bytes,2,opt,name=long_id,json=longId,proto3" json:"long_id,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Hostname             string      `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 uint32      `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	State                DeviceState `protobuf:"varint,6,opt,name=state,proto3,enum=DeviceState" json:"state,omitempty"`
	Connector            bool        `protobuf:"varint,7,opt,name=connector,proto3" json:"connector,omitempty"`
	Key                  []byte      `protobuf:"bytes,8,opt,name=key,proto3" json:"key,omitempty"`
	UseKey               bool        `protobuf:"varint,9,opt,name=use_key,json=useKey,proto3" json:"use_key,omitempty"`
	ChannelCnt           uint32      `protobuf:"varint,10,opt,name=channel_cnt,json=channelCnt,proto3" json:"channel_cnt,omitempty"`
	Uptime               int64       `protobuf:"varint,11,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Joined               uint64      `protobuf:"varint,12,opt,name=joined,proto3" json:"joined,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_d691f532c09db648, []int{0}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Device) GetLongId() string {
	if m != nil {
		return m.LongId
	}
	return ""
}

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Device) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Device) GetState() DeviceState {
	if m != nil {
		return m.State
	}
	return DeviceState_OFFLINE
}

func (m *Device) GetConnector() bool {
	if m != nil {
		return m.Connector
	}
	return false
}

func (m *Device) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Device) GetUseKey() bool {
	if m != nil {
		return m.UseKey
	}
	return false
}

func (m *Device) GetChannelCnt() uint32 {
	if m != nil {
		return m.ChannelCnt
	}
	return 0
}

func (m *Device) GetUptime() int64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *Device) GetJoined() uint64 {
	if m != nil {
		return m.Joined
	}
	return 0
}

type Channel struct {
	Id                   uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Device               uint64     `protobuf:"varint,3,opt,name=device,proto3" json:"device,omitempty"`
	Type                 MatrixType `protobuf:"varint,4,opt,name=type,proto3,enum=MatrixType" json:"type,omitempty"`
	Color                string     `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	MaxLength            uint32     `protobuf:"varint,6,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_d691f532c09db648, []int{1}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetDevice() uint64 {
	if m != nil {
		return m.Device
	}
	return 0
}

func (m *Channel) GetType() MatrixType {
	if m != nil {
		return m.Type
	}
	return MatrixType_SINGLEVALUE
}

func (m *Channel) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Channel) GetMaxLength() uint32 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

type Matrix struct {
	Id                   uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Device               uint64     `protobuf:"varint,2,opt,name=device,proto3" json:"device,omitempty"`
	Channel              uint64     `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Width                uint32     `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32     `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Type                 MatrixType `protobuf:"varint,6,opt,name=type,proto3,enum=MatrixType" json:"type,omitempty"`
	Coloring             string     `protobuf:"bytes,7,opt,name=coloring,proto3" json:"coloring,omitempty"`
	Offset               uint32     `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	Brightness           uint32     `protobuf:"varint,9,opt,name=brightness,proto3" json:"brightness,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Matrix) Reset()         { *m = Matrix{} }
func (m *Matrix) String() string { return proto.CompactTextString(m) }
func (*Matrix) ProtoMessage()    {}
func (*Matrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_d691f532c09db648, []int{2}
}

func (m *Matrix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matrix.Unmarshal(m, b)
}
func (m *Matrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matrix.Marshal(b, m, deterministic)
}
func (m *Matrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matrix.Merge(m, src)
}
func (m *Matrix) XXX_Size() int {
	return xxx_messageInfo_Matrix.Size(m)
}
func (m *Matrix) XXX_DiscardUnknown() {
	xxx_messageInfo_Matrix.DiscardUnknown(m)
}

var xxx_messageInfo_Matrix proto.InternalMessageInfo

func (m *Matrix) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Matrix) GetDevice() uint64 {
	if m != nil {
		return m.Device
	}
	return 0
}

func (m *Matrix) GetChannel() uint64 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *Matrix) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Matrix) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Matrix) GetType() MatrixType {
	if m != nil {
		return m.Type
	}
	return MatrixType_SINGLEVALUE
}

func (m *Matrix) GetColoring() string {
	if m != nil {
		return m.Coloring
	}
	return ""
}

func (m *Matrix) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Matrix) GetBrightness() uint32 {
	if m != nil {
		return m.Brightness
	}
	return 0
}

type MatrixUpdate struct {
	Matrix               uint64   `protobuf:"varint,1,opt,name=matrix,proto3" json:"matrix,omitempty"`
	Start                uint32   `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Pixels               []*Pixel `protobuf:"bytes,3,rep,name=pixels,proto3" json:"pixels,omitempty"`
	Frame                uint64   `protobuf:"varint,4,opt,name=frame,proto3" json:"frame,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatrixUpdate) Reset()         { *m = MatrixUpdate{} }
func (m *MatrixUpdate) String() string { return proto.CompactTextString(m) }
func (*MatrixUpdate) ProtoMessage()    {}
func (*MatrixUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_d691f532c09db648, []int{3}
}

func (m *MatrixUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatrixUpdate.Unmarshal(m, b)
}
func (m *MatrixUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatrixUpdate.Marshal(b, m, deterministic)
}
func (m *MatrixUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatrixUpdate.Merge(m, src)
}
func (m *MatrixUpdate) XXX_Size() int {
	return xxx_messageInfo_MatrixUpdate.Size(m)
}
func (m *MatrixUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MatrixUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MatrixUpdate proto.InternalMessageInfo

func (m *MatrixUpdate) GetMatrix() uint64 {
	if m != nil {
		return m.Matrix
	}
	return 0
}

func (m *MatrixUpdate) GetStart() uint32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *MatrixUpdate) GetPixels() []*Pixel {
	if m != nil {
		return m.Pixels
	}
	return nil
}

func (m *MatrixUpdate) GetFrame() uint64 {
	if m != nil {
		return m.Frame
	}
	return 0
}

type Pixel struct {
	R                    uint32   `protobuf:"varint,1,opt,name=R,proto3" json:"R,omitempty"`
	G                    uint32   `protobuf:"varint,2,opt,name=G,proto3" json:"G,omitempty"`
	B                    uint32   `protobuf:"varint,3,opt,name=B,proto3" json:"B,omitempty"`
	W                    uint32   `protobuf:"varint,4,opt,name=W,proto3" json:"W,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pixel) Reset()         { *m = Pixel{} }
func (m *Pixel) String() string { return proto.CompactTextString(m) }
func (*Pixel) ProtoMessage()    {}
func (*Pixel) Descriptor() ([]byte, []int) {
	return fileDescriptor_d691f532c09db648, []int{4}
}

func (m *Pixel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pixel.Unmarshal(m, b)
}
func (m *Pixel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pixel.Marshal(b, m, deterministic)
}
func (m *Pixel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pixel.Merge(m, src)
}
func (m *Pixel) XXX_Size() int {
	return xxx_messageInfo_Pixel.Size(m)
}
func (m *Pixel) XXX_DiscardUnknown() {
	xxx_messageInfo_Pixel.DiscardUnknown(m)
}

var xxx_messageInfo_Pixel proto.InternalMessageInfo

func (m *Pixel) GetR() uint32 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *Pixel) GetG() uint32 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *Pixel) GetB() uint32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *Pixel) GetW() uint32 {
	if m != nil {
		return m.W
	}
	return 0
}

type Project struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Created              uint64   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	LastUpdate           uint64   `protobuf:"varint,4,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Client               string   `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Active               bool     `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	FrontendState        []byte   `protobuf:"bytes,7,opt,name=frontend_state,json=frontendState,proto3" json:"frontend_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_d691f532c09db648, []int{5}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Project) GetLastUpdate() uint64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *Project) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *Project) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Project) GetFrontendState() []byte {
	if m != nil {
		return m.FrontendState
	}
	return nil
}

type User struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Created              uint64   `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	LastLogin            uint64   `protobuf:"varint,6,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d691f532c09db648, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *User) GetLastLogin() uint64 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

func init() {
	proto.RegisterEnum("DeviceState", DeviceState_name, DeviceState_value)
	proto.RegisterEnum("MatrixType", MatrixType_name, MatrixType_value)
	proto.RegisterType((*Device)(nil), "Device")
	proto.RegisterType((*Channel)(nil), "Channel")
	proto.RegisterType((*Matrix)(nil), "Matrix")
	proto.RegisterType((*MatrixUpdate)(nil), "MatrixUpdate")
	proto.RegisterType((*Pixel)(nil), "Pixel")
	proto.RegisterType((*Project)(nil), "Project")
	proto.RegisterType((*User)(nil), "User")
}

func init() { proto.RegisterFile("protobufs/api.proto", fileDescriptor_d691f532c09db648) }

var fileDescriptor_d691f532c09db648 = []byte{
	// 771 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdf, 0x6e, 0xa3, 0x46,
	0x14, 0xc6, 0x3b, 0x18, 0x83, 0x39, 0x36, 0x59, 0x3a, 0xdb, 0xa6, 0x28, 0xea, 0xee, 0x22, 0x4b,
	0x95, 0xd0, 0x5e, 0xa4, 0x55, 0xfa, 0x00, 0x95, 0x9d, 0x78, 0xbd, 0x56, 0x5d, 0x27, 0x9a, 0x38,
	0x8d, 0x7a, 0x85, 0x08, 0x8c, 0x6d, 0xb6, 0x78, 0x40, 0x30, 0xde, 0xb5, 0x9f, 0xa5, 0x8f, 0xd1,
	0x07, 0xe8, 0x13, 0xf5, 0x1d, 0xaa, 0x39, 0x8c, 0xff, 0xac, 0x56, 0x95, 0x72, 0xc7, 0xef, 0x1b,
	0x18, 0xce, 0xf7, 0x9d, 0x33, 0x03, 0x2f, 0xcb, 0xaa, 0x90, 0xc5, 0xd3, 0x66, 0x51, 0xff, 0x18,
	0x97, 0xd9, 0x25, 0x52, 0xff, 0x6f, 0x03, 0xac, 0x1b, 0xfe, 0x31, 0x4b, 0x38, 0x3d, 0x03, 0x23,
	0x4b, 0x7d, 0x12, 0x90, 0xd0, 0x64, 0x46, 0x96, 0xd2, 0xef, 0xc0, 0xce, 0x0b, 0xb1, 0x8c, 0xb2,
	0xd4, 0x37, 0x02, 0x12, 0x3a, 0xcc, 0x52, 0x38, 0x49, 0x29, 0x05, 0x53, 0xc4, 0x6b, 0xee, 0xb7,
	0x50, 0xc5, 0x67, 0x7a, 0x01, 0x9d, 0x55, 0x51, 0x4b, 0xd4, 0x4d, 0xd4, 0x0f, 0xac, 0xde, 0x2f,
	0x8b, 0x4a, 0xfa, 0xed, 0x80, 0x84, 0x2e, 0xc3, 0x67, 0xda, 0x87, 0x76, 0x2d, 0x63, 0xc9, 0x7d,
	0x2b, 0x20, 0xe1, 0xd9, 0x55, 0xef, 0xb2, 0x29, 0xe2, 0x5e, 0x69, 0xac, 0x59, 0xa2, 0xdf, 0x83,
	0x93, 0x14, 0x42, 0xf0, 0x44, 0x16, 0x95, 0x6f, 0x07, 0x24, 0xec, 0xb0, 0xa3, 0x40, 0x3d, 0x68,
	0xfd, 0xc9, 0x77, 0x7e, 0x27, 0x20, 0x61, 0x8f, 0xa9, 0x47, 0x55, 0xf0, 0xa6, 0xe6, 0x91, 0x52,
	0x1d, 0x7c, 0xdb, 0xda, 0xd4, 0xfc, 0x57, 0xbe, 0xa3, 0x6f, 0xa0, 0x9b, 0xac, 0x62, 0x21, 0x78,
	0x1e, 0x25, 0x42, 0xfa, 0x80, 0x75, 0x80, 0x96, 0xae, 0x85, 0xa4, 0xe7, 0x60, 0x6d, 0x4a, 0x99,
	0xad, 0xb9, 0xdf, 0x0d, 0x48, 0xd8, 0x62, 0x9a, 0x94, 0xfe, 0xa1, 0xc8, 0x04, 0x4f, 0xfd, 0x1e,
	0xc6, 0xa2, 0xa9, 0xff, 0x17, 0x01, 0xfb, 0xba, 0xf9, 0xfc, 0x8b, 0xd8, 0xf6, 0xe9, 0x18, 0x27,
	0xe9, 0x9c, 0x83, 0x95, 0xa2, 0x3f, 0xcc, 0xcc, 0x64, 0x9a, 0xe8, 0x1b, 0x30, 0xe5, 0xae, 0x6c,
	0x12, 0x3b, 0xbb, 0xea, 0x5e, 0xfe, 0x16, 0xcb, 0x2a, 0xdb, 0xce, 0x77, 0x25, 0x67, 0xb8, 0x40,
	0xbf, 0x81, 0x76, 0x52, 0xe4, 0x45, 0x85, 0xd9, 0x39, 0xac, 0x01, 0xfa, 0x0a, 0x60, 0x1d, 0x6f,
	0xa3, 0x9c, 0x8b, 0xa5, 0x5c, 0x61, 0x82, 0x2e, 0x73, 0xd6, 0xf1, 0x76, 0x8a, 0x42, 0xff, 0x5f,
	0x02, 0x56, 0xb3, 0xd3, 0x17, 0xc5, 0x1d, 0x0b, 0x31, 0x3e, 0x2b, 0xc4, 0x07, 0x5b, 0xc7, 0xa1,
	0x2b, 0xdc, 0xa3, 0xaa, 0xe0, 0x53, 0x96, 0xca, 0x15, 0xd6, 0xe8, 0xb2, 0x06, 0xd4, 0x3e, 0x2b,
	0x9e, 0x2d, 0x57, 0xfb, 0xa6, 0x6a, 0x3a, 0x18, 0xb2, 0xfe, 0xcf, 0xd0, 0x05, 0x74, 0xd0, 0x43,
	0x26, 0x96, 0xd8, 0x52, 0x87, 0x1d, 0x58, 0x6d, 0x5a, 0x2c, 0x16, 0x35, 0x97, 0xd8, 0x54, 0x97,
	0x69, 0xa2, 0xaf, 0x01, 0x9e, 0x2a, 0xb5, 0xbd, 0xe0, 0x75, 0x8d, 0xad, 0x75, 0xd9, 0x89, 0xd2,
	0xaf, 0xa0, 0xd7, 0xfc, 0xe7, 0xa1, 0x4c, 0xd5, 0xdc, 0x9c, 0x83, 0xb5, 0x46, 0xd6, 0xc6, 0x35,
	0x29, 0x2b, 0xb5, 0x8c, 0x2b, 0x89, 0xde, 0x5d, 0xd6, 0x00, 0x7d, 0x0d, 0x56, 0x99, 0x6d, 0x79,
	0x5e, 0xfb, 0xad, 0xa0, 0x15, 0x76, 0xaf, 0xac, 0xcb, 0x3b, 0x85, 0x4c, 0xab, 0xea, 0xab, 0x45,
	0xb5, 0x1f, 0x6b, 0x93, 0x35, 0xd0, 0xff, 0x05, 0xda, 0xf8, 0x1a, 0xed, 0x01, 0x61, 0xf8, 0x1f,
	0x97, 0x11, 0xa6, 0x68, 0xac, 0xb7, 0x27, 0x63, 0x45, 0x43, 0xcc, 0xd3, 0x65, 0x64, 0xa8, 0xe8,
	0x51, 0xa7, 0x48, 0x1e, 0xfb, 0xff, 0x10, 0xb0, 0xef, 0xaa, 0xe2, 0x03, 0x4f, 0xe4, 0xb3, 0x46,
	0x48, 0x75, 0xa8, 0xe2, 0xb1, 0xe4, 0xe9, 0xa1, 0x43, 0x0d, 0xaa, 0xe9, 0xce, 0xe3, 0x5a, 0x46,
	0x1b, 0x74, 0xaf, 0xcb, 0x04, 0x25, 0x1d, 0xf3, 0x48, 0xf2, 0x8c, 0x0b, 0xa9, 0xa7, 0x48, 0x93,
	0xd2, 0xe3, 0x44, 0x66, 0x1f, 0x9b, 0x76, 0x75, 0x98, 0x26, 0xfa, 0x03, 0x9c, 0x2d, 0xaa, 0x42,
	0x48, 0x2e, 0xd2, 0xa8, 0x39, 0xa4, 0x36, 0x1e, 0x32, 0x77, 0xaf, 0xe2, 0x29, 0x55, 0x87, 0xc0,
	0x7c, 0xa8, 0x79, 0xf5, 0xac, 0xf2, 0x2f, 0xa0, 0xb3, 0xa9, 0x79, 0x75, 0x72, 0x6f, 0x1c, 0x58,
	0xad, 0x95, 0x71, 0x5d, 0x7f, 0x2a, 0xaa, 0x74, 0x7f, 0x77, 0xec, 0xf9, 0xd4, 0x76, 0xfb, 0x73,
	0xdb, 0xaf, 0x00, 0x3d, 0x46, 0x79, 0xb1, 0xcc, 0x04, 0x3a, 0x30, 0x99, 0xa3, 0x94, 0xa9, 0x12,
	0xde, 0xee, 0xa0, 0x7b, 0x72, 0xa5, 0xd0, 0x2e, 0xd8, 0xb7, 0xef, 0xde, 0x4d, 0x27, 0xb3, 0x91,
	0xf7, 0x15, 0x7d, 0x09, 0x2f, 0xae, 0x6f, 0x67, 0xb3, 0xd1, 0xf5, 0x7c, 0x32, 0x1b, 0x47, 0x83,
	0x87, 0xf9, 0x7b, 0x8f, 0xd0, 0x6f, 0xe1, 0xeb, 0x13, 0xf1, 0xfd, 0x60, 0x3a, 0x1f, 0xdd, 0x78,
	0xc6, 0x89, 0x3c, 0xba, 0x89, 0x1e, 0x07, 0x13, 0xb5, 0xea, 0xb5, 0xa8, 0x0b, 0xce, 0xed, 0xdd,
	0x88, 0x0d, 0x10, 0x4d, 0xb5, 0xfd, 0xfd, 0x7c, 0x30, 0xbb, 0x19, 0xfe, 0xe1, 0xb5, 0xdf, 0xfe,
	0x04, 0x70, 0x9c, 0x7b, 0xfa, 0x02, 0xba, 0xf7, 0x93, 0xd9, 0x78, 0x3a, 0xfa, 0x7d, 0x30, 0x7d,
	0x50, 0x7f, 0xb7, 0xa1, 0xc5, 0xc6, 0x43, 0x8f, 0xd0, 0x0e, 0x98, 0x6c, 0x3c, 0x7c, 0xf4, 0x8c,
	0x27, 0x0b, 0x2f, 0xe3, 0x9f, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x13, 0xb7, 0x0c, 0xa3,
	0x05, 0x00, 0x00,
}
