/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.MatrixUpdate');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Pixel');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MatrixUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MatrixUpdate.repeatedFields_, null);
};
goog.inherits(proto.MatrixUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MatrixUpdate.displayName = 'proto.MatrixUpdate';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MatrixUpdate.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MatrixUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.MatrixUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MatrixUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MatrixUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
    matrix: jspb.Message.getFieldWithDefault(msg, 1, 0),
    start: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pixelsList: jspb.Message.toObjectList(msg.getPixelsList(),
    proto.Pixel.toObject, includeInstance),
    frame: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MatrixUpdate}
 */
proto.MatrixUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MatrixUpdate;
  return proto.MatrixUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MatrixUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MatrixUpdate}
 */
proto.MatrixUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMatrix(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStart(value);
      break;
    case 3:
      var value = new proto.Pixel;
      reader.readMessage(value,proto.Pixel.deserializeBinaryFromReader);
      msg.addPixels(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFrame(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MatrixUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MatrixUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MatrixUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MatrixUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMatrix();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getStart();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getPixelsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.Pixel.serializeBinaryToWriter
    );
  }
  f = message.getFrame();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
};


/**
 * optional uint64 matrix = 1;
 * @return {number}
 */
proto.MatrixUpdate.prototype.getMatrix = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.MatrixUpdate.prototype.setMatrix = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 start = 2;
 * @return {number}
 */
proto.MatrixUpdate.prototype.getStart = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.MatrixUpdate.prototype.setStart = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated Pixel pixels = 3;
 * @return {!Array<!proto.Pixel>}
 */
proto.MatrixUpdate.prototype.getPixelsList = function() {
  return /** @type{!Array<!proto.Pixel>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Pixel, 3));
};


/** @param {!Array<!proto.Pixel>} value */
proto.MatrixUpdate.prototype.setPixelsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.Pixel=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Pixel}
 */
proto.MatrixUpdate.prototype.addPixels = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.Pixel, opt_index);
};


proto.MatrixUpdate.prototype.clearPixelsList = function() {
  this.setPixelsList([]);
};


/**
 * optional uint64 frame = 4;
 * @return {number}
 */
proto.MatrixUpdate.prototype.getFrame = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.MatrixUpdate.prototype.setFrame = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


